project/articulo/urls.py
from django.urls import path
from . import views

app_name = 'articulo'

urlpatterns = [
    path("articulo/", views.home, name="home"),
    path("crear_articulo/", views.crear_articulo, name="crear_articulo"),

]

project/cliente/urls.py
from django.urls import path
from . import views

app_name = 'cliente'

urlpatterns = [
    path("cliente/", views.home, name="home"),
    path("crear_cliente/", views.crear_cliente, name="crear_cliente"),
    path("pedidos/", views.pedidos, name="pedidos"),
    path("crear_pedidos/", views.crear_pedido, name="crear_pedidos"),

]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('cliente/', include('cliente.urls')),
    path('articulo/', include('articulo.urls')),
]

project/core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name ='home'),
    path('about/', views.about, name ='about'),
]

project/articulo/models.py
from django.db import models

# Create your models here.
class Articulo(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre')
    descripcion = models.CharField(max_length=200, verbose_name='Descripción')
    precio =  models.CharField(max_length=200, verbose_name='Precio')

    def __str__(self):
        return f"{self.nombre} - ${self.precio}"
    
    class Meta:
        verbose_name_plural = "Artículos"
        verbose_name = 'Artículo'

project/cliente/models.py
from django.db import models
from articulo.models import Articulo

# Create your models here.


class Cliente(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre')
    apellido = models.CharField(max_length=200, verbose_name='Apellido')
    dni = models.CharField(max_length=8,verbose_name='DNI', unique=True)
    direccion =  models.CharField(max_length=200, verbose_name='Dirección')
    ciudad =  models.CharField(max_length=200, verbose_name='Ciudad', default='',null=False)

    def __str__(self):
        return f"{self.apellido}, {self.nombre}"
    
    class Meta:
        verbose_name_plural = "Clientes"
        verbose_name = 'Cliente'

class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.SET_NULL, null=True, blank=True,verbose_name='Cliente')
    articulo = models.ForeignKey(Articulo,on_delete=models.SET_NULL, null=True, blank=True,verbose_name='Artículo')
    cantidad = models.IntegerField(verbose_name='Cantidad', default=0)
    
    def __str__(self):
        return f"{self.cliente} - Art.: {self.articulo} Cantidad: {self.cantidad} "

project/core/models.py
from django.db import models

# Create your models here.

project/articulo/forms.py
from django import forms
from . import models

class ArticuloForm(forms.ModelForm):
    class Meta:
        model = models.Articulo
        fields = '__all__'
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "precio": forms.TextInput(attrs={"class": "form-control"}),
        }

project/cliente/forms.py
from django import forms
from . import models

class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = '__all__'
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "dni": forms.TextInput(attrs={"class": "form-control"}),
            "direccion": forms.TextInput(attrs={"class": "form-control"}),
            "ciudad": forms.TextInput(attrs={"class": "form-control"}),
        }

class PedidoForm(forms.ModelForm):
    class Meta:
        model = models.Pedido
        fields = '__all__'
        widgets = {
            "cliente": forms.Select(attrs={"class": "form-control"}),
            "articulo": forms.Select(attrs={"class": "form-control"}),
            "cantidad": forms.TextInput(attrs={"class": "form-control"}),
            
        }

project/articulo/views.py
from django.shortcuts import render, redirect
from . import models, forms
# Create your views here.
def home(request):
    consulta_articulos = models.Articulo.objects.all()
    context = {"articulos": consulta_articulos}
    return render(request, "articulo/index.html", context)

def crear_articulo(request):
    if request.method == "POST":
        form = forms.ArticuloForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articulo:home')
    else:
        form = forms.ArticuloForm()
    return render(request, 'articulo/crear_articulo.html', {'form': form})

project/cliente/views.py
from django.shortcuts import render, redirect
from . import models, forms

# Create your views here.
def home(request):
    consulta_clientes = models.Cliente.objects.all()
    context = {"clientes": consulta_clientes}
    return render(request, "cliente/index.html", context)


def crear_cliente(request):
    if request.method == "POST":
        form = forms.ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cliente:home')
    else:
        form = forms.ClienteForm()
    return render(request, 'cliente/crear_cliente.html', {'form': form})

def pedidos(request):
    consulta_pedidos = models.Pedido.objects.all()
    context = {"pedidos": consulta_pedidos}
    return render(request, "cliente/pedidos.html", context)

def crear_pedido(request):
    if request.method == "POST":
        form = forms.PedidoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cliente:pedidos')
    else:
        form = forms.PedidoForm()
    return render(request, 'cliente/crear_pedido.html', {'form': form})

project/core/views.py
from django.shortcuts import render
from articulo import models

# Create your views here.
def home(request):
    return render (request, 'core/index.html')

def about(request):
    return render (request, 'core/about.html')

project/articulo/templates/articulo/crear_articulo.html
{% extends 'core/base.html' %}

{% block titulo %}
    Crear Nuevo Articulo
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="table-responsive">
                            <table class="table">
                                {{ form.as_table }}
                            </table>
                        </div>
                        <button type="submit" class="btn btn-dark">Guardar</button>
                        <a href="{% url 'articulo:home' %}" class="btn btn-dark">Volver</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

project/articulo/templates/articulo/index.html
{% extends 'core/base.html' %}
{% block titulo %}
    Artículos
{% endblock titulo %}

{% block contenido %}
<div style="margin-left: 20px; margin-top: 10px; display: inline-block; background-color: #f8f8f8; color: #3498db; padding: 8px 16px; border-radius: 8px;">
    <a href="{% url 'articulo:crear_articulo' %}" style="color: #3498db; text-decoration: none;">Crear nuevo Artículo</a>
</div>
  
  
    <div class="my-4">
        <div class="container">
            <div class="row">
                {% for articulo in articulos %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <h2 class="card-title">{{ articulo.nombre }}</h2>
                                <h4 class="card-price">${{ articulo.precio }}</h4>
                                <p class="card-text">{{ articulo.descripcion }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
<div style="height: 50px;"></div>
{% endblock contenido %}

project/cliente/templates/cliente/crear_cliente.html
{% extends 'core/base.html' %}

{% block titulo %}
    Crear nuevo Cliente
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="table-responsive">
                            <table class="table">
                                {{ form.as_table }}
                            </table>
                        </div>
                        <button type="submit" class="btn btn-dark">Guardar</button>
                        <a href="{% url 'cliente:home' %}" class="btn btn-dark">Volver</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

project/cliente/templates/cliente/crear_pedido.html
{% extends 'core/base.html' %}

{% block titulo %}
    Crear nuevo Pedido
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="table-responsive">
                            <table class="table">
                                {{ form.as_table }}
                            </table>
                        </div>
                        <button type="submit" class="btn btn-dark">Guardar</button>
                        <a href="{% url 'cliente:pedidos' %}" class="btn btn-dark">Volver</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block titulo %}
    Clientes
{% endblock titulo %}

{% block contenido %}
<div style="margin-left: 20px; margin-top: 10px; display: inline-block; background-color: #f8f8f8; color: #3498db; padding: 8px 16px; border-radius: 8px;">
    <a href="{% url 'cliente:crear_cliente' %}" style="color: #3498db; text-decoration: none;">Crear nuevo Cliente</a>
</div>
    <style>
        .card {
            max-width: 18rem;
            margin-bottom: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            height: 100%; /* Establecer altura fija */
        }
        .card-body {
            padding: 15px;
            height: 100%; /* Asegurar que el cuerpo de la tarjeta ocupe toda la altura */
        }
        .card-title {
            margin-bottom: 5px;
            font-size: 1.2rem;
            color: #333;
        }
        .card-text {
            margin-bottom: 5px;
            font-size: 1rem;
            color: #666;
        }
        .card-text strong {
            color: #444;
        }
        .card-container {
            margin: 0 10px;
        }
    </style>
    <section class="clientes mt-4">
        <div class="row">
            {% for cliente in clientes %}
                <div class="col-md-3 mb-3">
                    <div class="card-container">
                        <div class="card">
                            <div class="card-body">
                                <h3 class="card-title">{{ cliente }}</h3>
                                <p class="card-text">
                                    <strong>DNI:</strong> {{ cliente.dni }}
                                </p>
                                <p class="card-text">
                                    <strong>Dirección:</strong> {{ cliente.direccion }}, {{ cliente.ciudad }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
<div style="height: 50px;"></div>
{% endblock contenido %}

project/cliente/templates/cliente/pedidos.html
{% extends 'core/base.html' %}

{% block titulo %}
    Pedidos registrados
{% endblock titulo %}

{% block contenido %}
<div style="margin-left: 20px; margin-top: 10px; display: inline-block; background-color: #f8f8f8; color: #3498db; padding: 8px 16px; border-radius: 8px;">
    <a href="{% url 'cliente:crear_pedidos' %}" style="color: #3498db; text-decoration: none;">Crear nuevo Pedido</a>
</div>
    <style>
        .card {
            max-width: 18rem;
            margin-bottom: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            height: 100%; /* Establecer altura fija */
        }
        .card-body {
            padding: 15px;
            height: 100%; /* Asegurar que el cuerpo de la tarjeta ocupe toda la altura */
        }
        .card-title {
            margin-bottom: 5px;
            font-size: 1.2rem;
            color: #333;
        }
        .card-text {
            margin-bottom: 5px;
            font-size: 1rem;
            color: #666;
        }
        .card-text strong {
            color: #444;
        }
        .card-container {
            margin: 0 10px;
        }
    </style>
    <section class="clientes mt-4">
        <div class="row">
            {% for pedido in pedidos %}
                <div class="col-md-3 mb-3">
                    <div class="card-container">
                        <div class="card">
                            <div class="card-body">
                                <h3 class="card-title">Cliente: {{ pedido.cliente }}</h3>
                                <p class="card-text">
                                    <strong>Artículo:</strong> {{ pedido.articulo }}
                                </p>
                                <p class="card-text">
                                    <strong>Cantidad:</strong>  {{ pedido.cantidad }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
<div style="height: 50px;"></div>
{% endblock contenido %}

project/core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
    About
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-0 shadow">
                <div class="card-body text-center">
                    <img src="{% static 'core/img/yo.webp' %}" class="mb-4" width="200" height="200" alt="Foto de perfil">
                    <h2 class="card-title mb-3">Cristian M. CARRIÓ</h2>
                    <p class="card-text" style="text-indent: 20px; text-align: justify;">
                        "Soy un profesor de informática apasionado por la programación y ansioso por convertirla en mi carrera principal. Me encanta enfrentarme a nuevos desafíos y establecer sólidos vínculos laborales mientras adquiero nuevas experiencias y conocimientos en el camino hacia el éxito profesional."
                    </p>
                    <p class="card-text"></p>
                    
                    <div class="social-links mt-4">
                        <a href="https://www.instagram.com/tincho900314/?next=%2F" class="instagram"><i class="fab fa-instagram"></i> Instagram</a>
                        <a href="https://github.com/Ccarrio90" class="github"><i class="fab fa-github"></i> GitHub</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="height: 100px;"></div>

{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            Pinturas "The Color Shop"
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        {% include 'core/components/navbar.html' %}
        <!-- Header-->
        {% include 'core/components/header.html' %}
        <!-- Section-->
        <div class="text-jusitfy text-bg-secondary bg-opacity-75    p-2 rounded">
            <h1 class="display-6  fw-normal ">
                {% block titulo %}
                {% endblock titulo %}
            </h1>
        </div>
        
        {% block contenido %}
        {% endblock contenido %}
       
        <!-- Footer-->
        {% include 'core/components/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/components/card.html
{% load static %}

<div class="col mb-5">
    <div class="card h-100">
        <!-- Product image-->
        <div style="max-height: 300px; overflow:hidden;">
            <img class="card-img-top w-100" src="{% static ruta %}" alt="..." style="object-fit: cover; object-position: center;" />
        </div>
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">{{ nombre }}</h5>
                <!-- Product price-->
                {{ precio }}
            </div>
        </div>
        <!-- Product actions-->
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
                <!-- Botón para abrir el modal -->
                <button type="button" class="btn btn-outline-dark mt-auto" data-bs-toggle="modal" data-bs-target="#myModal{{ nombre|slugify }}">
                    Descripción
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal{{ nombre|slugify }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Descripción</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Mostrar la descripción -->
                <p>{{ descripcion }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

project/core/templates/core/components/footer.html
<footer class="py-3" style="background-color: #f5f5dc;">
    <div class="container">
        <p class="m-0 text-center text-dark">Pre-entrega © CoderHouse 2024</p>
    </div>
</footer>

project/core/templates/core/components/header.html
<header class="bg-dark py-1">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">🖌️Pinturas "The Color Shop🎨"</h1>
            <p class="lead fw-normal text-white-50 mb-0">"Transformando hogares con una paleta infinita de colores vibrantes y tonos sutiles. ¡Encuentra tu inspiración en The Color Shop hoy!".</p>
        </div>
    </div>
</header>

project/core/templates/core/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f5f5dc;">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'core:home' %}">Pinturerias</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'cliente:home' %}">Clientes</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'articulo:home' %}">Artículos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'cliente:pedidos' %}">Pedidos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">About</a></li>
                <li class="nav-item dropdown">
                </li>
            </ul>
            <form class="d-flex">
            </form>
        </div>
    </div>
</nav>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    ¡Ofertas!
{% endblock titulo %}


{% block contenido %}
<section class="py-5">
    <div class="container px-4 px-lg-6 mt-2">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% include 'core/components/card.html' with nombre='Recuplast - Frentes ' precio='$151.000' ruta='core/img/imagen1.webp' descripcion='"Protege tu hogar con nuestra pintura impermeable para frentes, resistente a la intemperie y de larga duración, para una belleza que perdura.'%}
            {% include 'core/components/card.html' with nombre='Rodillos - Varios' precio='$142.000' ruta='core/img/imagen2.webp' descripcion='Obtén resultados profesionales con nuestros rodillos de alta calidad, diseñados para una aplicación suave y uniforme en cada proyecto de pintura.'%}
            {% include 'core/components/card.html' with nombre='Pinceles' precio='$95.000' ruta='core/img/imagen3.webp' descripcion='Descubre la precisión y versatilidad en cada trazo con nuestros pinceles de calidad premium, tu herramienta indispensable para crear obras maestras.'%}
            {% include 'core/components/card.html' with nombre='Sopletes' precio='$235.000' ruta='core/img/imagen4.webp' descripcion='Domina el arte de la pintura con nuestros sopletes de alta precisión, tu compañero confiable para aplicaciones eficientes y acabados profesionales.'%}
            
        </div>
    </div>
</section>
{% endblock contenido %}